    runtime: python313 # Or your desired Python version
    entrypoint: gunicorn -b :$PORT myproject.wsgi # Replace myproject with your project name

    env_variables:
        DJANGO_SETTINGS_MODULE: myproject.settings

    handlers:
    - url: /static
      static_dir: static
    - url: /.*
      script: auto